### ISSUE TITLE
Using mod cause crash 1.14.4 fabric

### ISSUE THREAD

**Issue by JestemZbychu** [Draylar/vanilla-hammers#36]
I know it's an old version but maybe someone can point where i did F up.
I instaled fabric + api, run it and then added VH and than it crashed. I've tried every 1.14.4 version with no effect
[crash-2020-02-11_19.19.29-client.txt](https://github.com/Draylar/vanilla-hammers/files/4187422/crash-2020-02-11_19.19.29-client.txt)
I can provide more info if needed.

**Comment by Levoment** [comment]
Everytime I get those errors is either because the mod version I am using is not for the version of the game, or because of something on the API. 
<br>
In this case, I get the same error on that API. Try ***[1.14.4] Fabric API 0.4.1 build 245*** instead of ***[1.14.4] Fabric API 0.4.2 build 246***. Build 245 seems to be working.

**Comment by JestemZbychu** [comment]
Thanks it worked <3
But now i need to live without optifabric ;/
