### ISSUE TITLE
[Bug] Crash on 20w13b

### ISSUE THREAD

**Issue by Mantarri** [Draylar/vanilla-hammers#43]
I'm getting a crash in 20w13b if I have a hammer in my inventory
[Crash log](https://paste.ubuntu.com/p/MVq5NFPZTd/)

**Comment by Mantarri** [comment]
Seems the problem only occurs if the hammer is in my hotbar.

**Comment by SkillHeaven** [comment]
The game crashes when you hold the hammer in your hand. It can be on the hotbar, but not in your hand. To add to this, you can not reenter your game world, because it is still in your hand. You have to completely remove the mod, and lose the items you used to make the hammer.  

[Crash-Report](https://pastebin.com/a9igMgvH)

**Comment by Mantarri** [comment]
Ah, I didn't realize it was being in one's hand specifically that caused it.
By the way, if you're running a server, you can have another play run `/clear YourPlayerNameHere vanilla-hammers:iron-hammer` replacing `iron-hammer` with the hammer in your hand, you can even specify how many of them to remove by adding the number at the end `/clear YourPlayerNameHere vanilla-hammers:iron-hammer 2`, you might also be able to use an NBT editor to remove it from your inventory in the case of singleplayer worlds, but I'm not sure how it interacts with non-vanilla items in an inventory.

**Comment by SkillHeaven** [comment]
I found it just easier to remove the mod and move on. It doesn't seem to make a difference. The other options are just more work.

**Comment by Draylar** [comment]
Just pushed an update for 20w14a. Thanks!
